name: CI

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '14'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Clean and Build project
        run: |
          ./gradlew clean
          ./gradlew build --parallel -Dgithub_name=github

      # https://github.com/marketplace/actions/test-reporter
#      - name: Generate unit test Report
#        uses: dorny/test-reporter@v1
#        if: (success() || failure()) && hashFiles('"target/test-results/**/*.xml"') != ''
#        with:
#          name: Unit Test Results
#          path: target/test-results/**/*.xml
#          reporter: 'java-junit'